from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font("helvetica", "B", 16)
        self.cell(0, 10, "MCS-26 - M1101 - LAB 01 - CAESAR CIPHER", new_x="LMARGIN", new_y="NEXT", align="C")
        self.ln(5)

pdf = PDF()
pdf.set_margins(left=20, top=15, right=20)
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()

# Group Members
pdf.set_font("helvetica", "B", 12)
pdf.cell(0, 10, "Group Members:", new_x="LMARGIN", new_y="NEXT", align="C")
pdf.set_font("helvetica", "", 11)
members = [
    "1. Lt Col Mamun (ID-007)",
    "2. Lt Col Hasnat (ID-005)",
    "3. Shaon Mir (ID-026)",
    "4. Moniruzzaman (ID-012)"
]
for m in members:
    pdf.cell(0, 8, m, new_x="LMARGIN", new_y="NEXT", align="C")
pdf.ln(10)

def add_heading(text):
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 51, 102) # Dark blue
    pdf.cell(0, 10, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("helvetica", "", 11)

def add_subheading(text):
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 8, text, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)

def add_text(text):
    pdf.multi_cell(0, 6, text, new_x="LMARGIN", new_y="NEXT")

def add_code(text):
    pdf.set_font("courier", "", 10)
    pdf.multi_cell(0, 6, text, fill=False, new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)
    pdf.ln(2)

# Ex 1.1
add_heading("Exercise 1.1 - Encrypt and decrypt")

add_subheading("a) Encrypt 'cryptography is fun' using k = 7.")
add_text("Numeric calculations for each letter:")
add_code("""c (2) + 7 = 9 % 26 = 9 (j)
r (17) + 7 = 24 % 26 = 24 (y)
y (24) + 7 = 31 % 26 = 5 (f)
p (15) + 7 = 22 % 26 = 22 (w)
t (19) + 7 = 26 % 26 = 0 (a)
o (14) + 7 = 21 % 26 = 21 (v)
g (6) + 7 = 13 % 26 = 13 (n)
r (17) + 7 = 24 % 26 = 24 (y)
a (0) + 7 = 7 % 26 = 7 (h)
p (15) + 7 = 22 % 26 = 22 (w)
h (7) + 7 = 14 % 26 = 14 (o)
y (24) + 7 = 31 % 26 = 5 (f)
i (8) + 7 = 15 % 26 = 15 (p)
s (18) + 7 = 25 % 26 = 25 (z)
f (5) + 7 = 12 % 26 = 12 (m)
u (20) + 7 = 27 % 26 = 1 (b)
n (13) + 7 = 20 % 26 = 20 (u)""")
add_text("Resulting ciphertext (spaces preserved):")
add_code("jyfwavnyhwof pz mbu")

add_subheading("b) Decrypt the result and verify you get the original text back.")
add_text('By running decrypt("jyfwavnyhwof pz mbu", 7), the cipher shifts each letter back by 7, which correctly yields the plaintext:')
add_code("cryptography is fun")

add_subheading("c) Repeat with k = 19 (rot-19) and verify symmetry.")
add_text('By encrypting the ciphertext "jyfwavnyhwof pz mbu" with k = 19, we get "cryptography is fun". This verifies symmetry because 7 + 19 = 26. A forward shift of 19 is mathematically equivalent to a backward shift of 7 (mod 26).')
pdf.ln(5)

# Ex 1.2
add_heading("Exercise 1.2 - Brute-force attack")
add_text("Ciphertext to break:")
add_code("MYXQVBKX ZKBDEOKX LOXGXXKVBOBK")

add_subheading("a) Run the brute-force function on it and identify the key.")
add_text("By running the brute_force function and minimizing the chi-squared score against English letter frequencies, we identify the key.")
add_text("Recovered Key: 10")

add_subheading("b) What is the plaintext?")
add_code("CONGLRAN PARTUEAN BENWNNALRERA")

add_subheading("c) How many operations did the brute-force require? Would this be feasible by hand?")
add_text("The brute-force attack requires 25 operations (trying all non-trivial shift values from 1 to 25) and observing which plaintext makes sense or has the lowest chi-squared score. Since 25 shifts is a very small number, this is entirely feasible to do by hand (especially if only decrypting the first few characters to check for English words).")
pdf.ln(5)

# Ex 1.3
pdf.add_page()
add_heading("Exercise 1.3 - Frequency analysis")

add_subheading("a) Encrypted text with a key of choice.")
add_text("We used a 1299-character excerpt from the Wikipedia page on Cryptography and encrypted it with a key of 12.")

add_subheading("b) Plot the letter-frequency histogram of the ciphertext.")
add_text("The plot was successfully generated by the script and saved as 'caesar_freq.pdf'.")

add_subheading("c) Use find_key_frequency() to recover the key automatically.")
add_text("The algorithm successfully recovered the key: 12")

add_subheading("d) Report the recovered key and the chi-squared scores for all 26 candidates.")
add_text("Recovered Key: 12")
add_code("""Chi-squared scores:
   0    2456.7605
   1    1160.3936
   2     833.4547
   3     920.8551
   4    1848.9461
   5     769.9516
   6    1729.7959
   7    1378.4573
   8     680.4035
   9     745.7314
  10     952.4928
  11     798.5241
  12      12.7510 <-- best
  13    1415.5140
  14     464.3837
  15    1709.7229
  16     760.4735
  17    2944.8975
  18     400.5273
  19    1261.5629
  20     884.8110
  21    1270.1510
  22    1045.9697
  23     473.5900
  24     563.1118
  25     428.6308""")
pdf.ln(5)

# Ex 1.4
pdf.add_page()
add_heading("Exercise 1.4 - Security evaluation")

# Create a proper table
table_data = [
    ("Property", "Caesar Cipher"),
    ("1. Key space size", "26 (or 25 non-trivial)"),
    ("2. Time to brute-force (at 10^9 keys/sec)", "2.6 x 10^-8 seconds"),
    ("3. Vulnerable to frequency analysis?", "Yes"),
    ("4. Index of Coincidence (ciphertext vs English)", "Same (~0.065)"),
    ("5. Attack type that breaks it", "Frequency Analysis / Brute-Force")
]

col_widths = [85, 85]
line_height = 8

pdf.set_font("helvetica", "B", 11)
pdf.set_fill_color(220, 220, 220)
# Header
for i, datum in enumerate(table_data[0]):
    pdf.cell(col_widths[i], line_height, datum, border=1, align="C", fill=True)
pdf.ln(line_height)

pdf.set_font("helvetica", "", 11)
pdf.set_fill_color(255, 255, 255)
# Rows
for row in table_data[1:]:
    for i, datum in enumerate(row):
        pdf.cell(col_widths[i], line_height, "  " + datum, border=1)
    pdf.ln(line_height)

pdf.output("lab1_report.pdf")
print("PDF created successfully with nice formatting.")
